// Single source of truth for Material Symbols Outlined icons used in this app.
// Google Fonts `icon_names=` parameter only loads these icons (~20KB vs ~2MB full).
//
// To add a new icon:
//   1. Use it: <span class="material-symbols-outlined">icon_name</span>
//   2. Add the name here (lowercase + underscore, alphabetical order)
//   3. Rebuild
//
// Browse: https://fonts.google.com/icons

export const MATERIAL_ICONS = [
  "accessibility",
  "account_balance",
  "account_box",
  "account_circle",
  "add",
  "add_circle",
  "admin_panel_settings",
  "alternate_email",
  "arrow_back",
  "arrow_forward",
  "article",
  "auto_stories",
  "badge",
  "block",
  "build",
  "calendar_today",
  "call",
  "campaign",
  "cancel",
  "chat",
  "check",
  "check_circle",
  "close",
  "construction",
  "contact_support",
  "credit_card",
  "dashboard",
  "delete",
  "description",
  "download",
  "edit",
  "edit_note",
  "electric_meter",
  "email",
  "emoji_events",
  "error",
  "event",
  "event_busy",
  "expand_more",
  "family_restroom",
  "folder",
  "group",
  "home",
  "how_to_reg",
  "inbox",
  "info",
  "kitchen",
  "location_on",
  "lock",
  "login",
  "logout",
  "mail",
  "map",
  "picture_as_pdf",
  "menu",
  "menu_book",
  "newspaper",
  "open_in_new",
  "pending",
  "person",
  "person_add",
  "play_arrow",
  "preview",
  "priority_high",
  "progress_activity",
  "public",
  "rate_review",
  "receipt",
  "refresh",
  "save",
  "schedule",
  "school",
  "search",
  "send",
  "settings",
  "shield_person",
  "stars",
  "tag",
  "task_alt",
  "timer",
  "toggle_off",
  "toggle_on",
  "upload",
  "upload_file",
  "verified",
  "verified_user",
  "visibility",
  "warning",
  "weekend",
  "workspace_premium",
] as const;

export function materialIconsHref(): string {
  const base = "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200";
  const names = [...MATERIAL_ICONS].sort().join(",");
  return `${base}&icon_names=${names}&display=swap`;
}
